[tool.poetry]
name = "victoria"
version = "0.1.0"
description = ""
authors = ["Krystof Albrecht <krystofalbrechtus@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.2.16"


langchain-ollama = "^0.1.3"
flask = "^3.0.3"
argparse = "^1.4.0"
waitress = "^3.0.0"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
victoria = "victoria.backend:main"
