name: Run project tests
on: [push, pull_request]

env:
  NIX_CONFIG: "experimental-features = nix-command flakes"

jobs:
  run-tests:
    runs-on: nixos-nix
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        ssh-key: ${{ secrets.ACTIONS_KEY }}

      - name: Enter development shell and run tests
        run: |
          nix develop --command bash -c '
            cd victoria-frontend
            npm install
            npm run test

            cd ../victoria-backend
            poetry install
            poetry run pytest
          '