"""add user roles

Revision ID: b8a5a21d9c62
Revises: c33ca2dd284c
Create Date: 2025-07-23 18:47:40.035973+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a5a21d9c62'
down_revision: Union[str, Sequence[str], None] = 'c33ca2dd284c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('USER', 'ADMIN', name='role', native_enum=False), nullable=False, server_default='USER'))
    op.alter_column('user', 'role', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
