"""add function data to action

Revision ID: bc39391eaf60
Revises: ced874008f1e
Create Date: 2025-09-06 19:22:21.064367+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc39391eaf60'
down_revision: Union[str, Sequence[str], None] = 'ced874008f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('function_param_schema', sa.JSON(), nullable=False))
    op.add_column('action', sa.Column('function_source_code', sa.Text(), nullable=False))
    op.add_column('action', sa.Column('function_docstring', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'function_docstring')
    op.drop_column('action', 'function_source_code')
    op.drop_column('action', 'function_param_schema')
    # ### end Alembic commands ###
