"""add llm models

Revision ID: f937008fe45b
Revises: 13ff3b824722
Create Date: 2025-09-06 10:30:09.142929+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f937008fe45b'
down_revision: Union[str, Sequence[str], None] = '13ff3b824722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['llm_connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_connection_ollama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['llm_connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent', sa.Column('model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agent', 'language_model', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent', type_='foreignkey')
    op.drop_column('agent', 'model_id')
    op.drop_table('llm_connection_ollama')
    op.drop_table('language_model')
    op.drop_table('llm_connection')
    # ### end Alembic commands ###
