"""thought invocation nullable

Revision ID: 055d9af392bd
Revises: 8a1933c3ebe6
Create Date: 2025-09-04 16:01:35.822764+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055d9af392bd'
down_revision: Union[str, Sequence[str], None] = '8a1933c3ebe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thought', 'invocation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thought', 'invocation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
