"""add context to monologue

Revision ID: 2cc641551e69
Revises: 1c0667397b91
Create Date: 2025-09-08 10:46:15.215901+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc641551e69'
down_revision: Union[str, Sequence[str], None] = '1c0667397b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monologue', sa.Column('context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monologue', 'context')
    # ### end Alembic commands ###
