"""handle invalid invocations

Revision ID: 13ff3b824722
Revises: b5e58e5d0567
Create Date: 2025-09-04 19:04:33.075734+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ff3b824722'
down_revision: Union[str, Sequence[str], None] = 'b5e58e5d0567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invocation', sa.Column('function_name', sa.String(length=80), nullable=False))
    op.alter_column('invocation', 'action_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invocation', 'action_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('invocation', 'function_name')
    # ### end Alembic commands ###
