"""add chat models

Revision ID: 06d93f7bce20
Revises: 67fd1217f990
Create Date: 2025-09-28 14:24:02.935200+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d93f7bce20'
down_revision: Union[str, Sequence[str], None] = '67fd1217f990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.String(length=180), nullable=False),
    sa.Column('receiver', sa.String(length=30), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allowed_chat_action',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE')
    )
    op.create_table('chat_exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('usermsg_exchange_id', sa.Integer(), nullable=True),
    sa.Column('reply_exchange_id', sa.Integer(), nullable=True),
    sa.Column('sending_agent_id', sa.Integer(), nullable=True),
    sa.Column('sending_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reply_exchange_id'], ['chat_exchange.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sending_agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['sending_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['usermsg_exchange_id'], ['chat_exchange.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usermsg_exchange_id')
    )
    op.create_table('chat_message_markdown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['chat_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('allowed_agent_action_action_id_fkey'), 'allowed_agent_action', type_='foreignkey')
    op.drop_constraint(op.f('allowed_agent_action_agent_id_fkey'), 'allowed_agent_action', type_='foreignkey')
    op.create_foreign_key(None, 'allowed_agent_action', 'action', ['action_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'allowed_agent_action', 'agent', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('allowed_agent_trigger_agent_id_fkey'), 'allowed_agent_trigger', type_='foreignkey')
    op.drop_constraint(op.f('allowed_agent_trigger_trigger_id_fkey'), 'allowed_agent_trigger', type_='foreignkey')
    op.create_foreign_key(None, 'allowed_agent_trigger', 'agent', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'allowed_agent_trigger', 'trigger', ['trigger_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'allowed_agent_trigger', type_='foreignkey')
    op.drop_constraint(None, 'allowed_agent_trigger', type_='foreignkey')
    op.create_foreign_key(op.f('allowed_agent_trigger_trigger_id_fkey'), 'allowed_agent_trigger', 'trigger', ['trigger_id'], ['id'])
    op.create_foreign_key(op.f('allowed_agent_trigger_agent_id_fkey'), 'allowed_agent_trigger', 'agent', ['agent_id'], ['id'])
    op.drop_constraint(None, 'allowed_agent_action', type_='foreignkey')
    op.drop_constraint(None, 'allowed_agent_action', type_='foreignkey')
    op.create_foreign_key(op.f('allowed_agent_action_agent_id_fkey'), 'allowed_agent_action', 'agent', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('allowed_agent_action_action_id_fkey'), 'allowed_agent_action', 'action', ['action_id'], ['id'])
    op.drop_table('chat_message_markdown')
    op.drop_table('chat_message')
    op.drop_table('chat_exchange')
    op.drop_table('allowed_chat_action')
    op.drop_table('chat')
    # ### end Alembic commands ###
