"""add monologue models

Revision ID: 64a072f5ff5b
Revises: b8a5a21d9c62
Create Date: 2025-07-27 16:50:38.118121+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64a072f5ff5b'
down_revision: Union[str, Sequence[str], None] = 'b8a5a21d9c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allowed_agent_trigger',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger.id'], )
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invocation_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_name', sa.String(length=60), nullable=False),
    sa.Column('param_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['invocation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invocation_failure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['invocation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invocation_success',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['invocation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invocation_thought',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['invocation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiver', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['trigger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['trigger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_timer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['trigger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=70), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['trigger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invocation_trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['id'], ['invocation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monologue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('summary', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILURE', name='monologuestatus', native_enum=False), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thought',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invocation_id', sa.Integer(), nullable=False),
    sa.Column('monologue_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invocation_id'], ['invocation.id'], ),
    sa.ForeignKeyConstraint(['monologue_id'], ['monologue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thought')
    op.drop_table('monologue')
    op.drop_table('invocation_trigger')
    op.drop_table('trigger_webhook')
    op.drop_table('trigger_timer')
    op.drop_table('trigger_poll')
    op.drop_table('trigger_chat')
    op.drop_table('invocation_thought')
    op.drop_table('invocation_success')
    op.drop_table('invocation_failure')
    op.drop_table('invocation_action')
    op.drop_table('event')
    op.drop_table('allowed_agent_trigger')
    op.drop_table('trigger')
    op.drop_table('invocation')
    op.drop_table('agent')
    # ### end Alembic commands ###
