"""increase llm name limit

Revision ID: 2f562b4ea400
Revises: 9a1df89663f5
Create Date: 2025-10-30 16:17:25.513215+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f562b4ea400'
down_revision: Union[str, Sequence[str], None] = '9a1df89663f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language_model', 'name',
               existing_type=sa.String(length=50),
               type_=sa.String(length=400),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language_model', 'name',
               existing_type=sa.String(length=400),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
