"""cascade agent deletes to monologues

Revision ID: 8c0622c48735
Revises: 8b652c2b9abc
Create Date: 2025-10-11 13:08:43.559063+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0622c48735'
down_revision: Union[str, Sequence[str], None] = '8b652c2b9abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'trigger_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('monologue_agent_id_fkey'), 'monologue', type_='foreignkey')
    op.create_foreign_key(None, 'monologue', 'agent', ['agent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monologue', type_='foreignkey')
    op.create_foreign_key(op.f('monologue_agent_id_fkey'), 'monologue', 'agent', ['agent_id'], ['id'])
    op.alter_column('event', 'trigger_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
