"""cascade action delete

Revision ID: e2cfb759867d
Revises: d4d3c94cff9c
Create Date: 2025-09-08 20:03:53.785802+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cfb759867d'
down_revision: Union[str, Sequence[str], None] = 'd4d3c94cff9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('action_repository_id_fkey'), 'action', type_='foreignkey')
    op.create_foreign_key(None, 'action', 'action_repository', ['repository_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action', type_='foreignkey')
    op.create_foreign_key(op.f('action_repository_id_fkey'), 'action', 'action_repository', ['repository_id'], ['id'])
    # ### end Alembic commands ###
