"""add model for action repository

Revision ID: 1c0667397b91
Revises: bc39391eaf60
Create Date: 2025-09-08 10:34:05.938586+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0667397b91'
down_revision: Union[str, Sequence[str], None] = 'bc39391eaf60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('action', sa.Column('repository_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'action', 'action_repository', ['repository_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action', type_='foreignkey')
    op.drop_column('action', 'repository_id')
    op.drop_table('action_repository')
    # ### end Alembic commands ###
