"""add timestamps to monologues

Revision ID: 8cafac607c14
Revises: 21ccba515e70
Create Date: 2025-10-13 10:35:10.628647+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cafac607c14'
down_revision: Union[str, Sequence[str], None] = '21ccba515e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monologue', sa.Column('dispatched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('monologue', sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monologue', 'modified_at')
    op.drop_column('monologue', 'dispatched_at')
    # ### end Alembic commands ###
