"""add thought timestamp

Revision ID: b5e58e5d0567
Revises: 055d9af392bd
Create Date: 2025-09-04 16:33:33.453605+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e58e5d0567'
down_revision: Union[str, Sequence[str], None] = '055d9af392bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thought', sa.Column('timestamp', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thought', 'timestamp')
    # ### end Alembic commands ###
