"""add answer field to choice prompt

Revision ID: 8b652c2b9abc
Revises: d1a0be8b9e84
Create Date: 2025-10-11 11:34:32.542245+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b652c2b9abc'
down_revision: Union[str, Sequence[str], None] = 'd1a0be8b9e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message_prompt', sa.Column('answer', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message_prompt', 'answer')
    # ### end Alembic commands ###
