"""enabled model attribute

Revision ID: ece92072bd62
Revises: f937008fe45b
Create Date: 2025-09-06 12:50:07.040239+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece92072bd62'
down_revision: Union[str, Sequence[str], None] = 'f937008fe45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_model', sa.Column('enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language_model', 'enabled')
    # ### end Alembic commands ###
