"""remove invocation subclasses

Revision ID: 8a1933c3ebe6
Revises: c8aac2226089
Create Date: 2025-09-04 15:49:54.793905+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1933c3ebe6'
down_revision: Union[str, Sequence[str], None] = 'c8aac2226089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invocation_failure')
    op.drop_table('invocation_trigger')
    op.drop_table('invocation_success')
    op.drop_table('invocation_action')
    op.drop_table('invocation_thought')
    op.add_column('invocation', sa.Column('action_id', sa.Integer(), nullable=False))
    op.add_column('invocation', sa.Column('params', sa.JSON(), nullable=False))
    op.create_foreign_key(None, 'invocation', 'action', ['action_id'], ['id'])
    op.drop_column('invocation', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invocation', sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invocation', type_='foreignkey')
    op.drop_column('invocation', 'params')
    op.drop_column('invocation', 'action_id')
    op.create_table('invocation_thought',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['invocation.id'], name=op.f('invocation_thought_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invocation_thought_pkey'))
    )
    op.create_table('invocation_action',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('function_name', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('param_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['invocation.id'], name=op.f('invocation_action_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invocation_action_pkey'))
    )
    op.create_table('invocation_success',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['invocation.id'], name=op.f('invocation_success_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invocation_success_pkey'))
    )
    op.create_table('invocation_trigger',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('invocation_trigger_event_id_fkey')),
    sa.ForeignKeyConstraint(['id'], ['invocation.id'], name=op.f('invocation_trigger_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invocation_trigger_pkey'))
    )
    op.create_table('invocation_failure',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['invocation.id'], name=op.f('invocation_failure_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invocation_failure_pkey'))
    )
    # ### end Alembic commands ###
