"""add choice message

Revision ID: 171bd244fd2e
Revises: 06d93f7bce20
Create Date: 2025-09-28 15:02:17.430910+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171bd244fd2e'
down_revision: Union[str, Sequence[str], None] = '06d93f7bce20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message_prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['chat_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message_prompt_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message_prompt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message_prompt_option')
    op.drop_table('chat_message_prompt')
    # ### end Alembic commands ###
