"""remove ChatEvent model

Revision ID: b0dc8bfb058d
Revises: 2f562b4ea400
Create Date: 2025-10-31 14:21:15.823567+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0dc8bfb058d'
down_revision: Union[str, Sequence[str], None] = '2f562b4ea400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_chat')
    op.add_column('event', sa.Column('triggering_chat_exchange_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_event_triggering_chat_exchange_id_chat_exchange'), 'event', 'chat_exchange', ['triggering_chat_exchange_id'], ['id'])
    op.drop_column('event', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('type', sa.String(length=10), autoincrement=False, nullable=False, server_default="BASE"))
    op.drop_constraint(op.f('fk_event_triggering_chat_exchange_id_chat_exchange'), 'event', type_='foreignkey')
    op.drop_column('event', 'triggering_chat_exchange_id')
    op.create_table('event_chat',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('triggering_chat_exchange_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['event.id'], name=op.f('fk_event_chat_id_event')),
    sa.ForeignKeyConstraint(['triggering_chat_exchange_id'], ['chat_exchange.id'], name=op.f('fk_event_chat_triggering_chat_exchange_id_chat_exchange')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_chat'))
    )
    # ### end Alembic commands ###
