"""support invalid invocations

Revision ID: d4d3c94cff9c
Revises: 2cc641551e69
Create Date: 2025-09-08 13:12:04.148480+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4d3c94cff9c'
down_revision: Union[str, Sequence[str], None] = '2cc641551e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invocation', sa.Column('function_name_semantically_valid', sa.Boolean(), nullable=False))
    op.add_column('invocation', sa.Column('params_semantically_valid', sa.Boolean(), nullable=False))
    op.alter_column('invocation', 'function_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('invocation', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invocation', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('invocation', 'function_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('invocation', 'params_semantically_valid')
    op.drop_column('invocation', 'function_name_semantically_valid')
    # ### end Alembic commands ###
