"""add chat event

Revision ID: b45b191b386f
Revises: 171bd244fd2e
Create Date: 2025-09-28 15:28:24.000645+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45b191b386f'
down_revision: Union[str, Sequence[str], None] = '171bd244fd2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triggering_chat_exchange_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['triggering_chat_exchange_id'], ['chat_exchange.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event', sa.Column('type', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'type')
    op.drop_table('event_chat')
    # ### end Alembic commands ###
