"""add monologue agent token

Revision ID: eec3de535692
Revises: 8cafac607c14
Create Date: 2025-10-26 13:15:52.647736+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec3de535692'
down_revision: Union[str, Sequence[str], None] = '8cafac607c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monologue', sa.Column('agent_token', sa.LargeBinary(length=32), nullable=True))
    op.create_unique_constraint(op.f('uq_monologue_agent_token'), 'monologue', ['agent_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_monologue_agent_token'), 'monologue', type_='unique')
    op.drop_column('monologue', 'agent_token')
    # ### end Alembic commands ###
