"""add owner to agents

Revision ID: d1a0be8b9e84
Revises: 0aa8093342cb
Create Date: 2025-10-06 10:22:19.082249+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a0be8b9e84'
down_revision: Union[str, Sequence[str], None] = '0aa8093342cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'agent', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent', type_='foreignkey')
    op.drop_column('agent', 'owner_id')
    # ### end Alembic commands ###
