"""cascade delete connection

Revision ID: ced874008f1e
Revises: ece92072bd62
Create Date: 2025-09-06 13:41:12.903542+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced874008f1e'
down_revision: Union[str, Sequence[str], None] = 'ece92072bd62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('language_model_connection_id_fkey'), 'language_model', type_='foreignkey')
    op.create_foreign_key(None, 'language_model', 'llm_connection', ['connection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'language_model', type_='foreignkey')
    op.create_foreign_key(op.f('language_model_connection_id_fkey'), 'language_model', 'llm_connection', ['connection_id'], ['id'])
    # ### end Alembic commands ###
