"""initial migration

Revision ID: 0aa8093342cb
Revises: 
Create Date: 2025-10-04 11:32:27.155182+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa8093342cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='role', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_name', sa.String(length=80), nullable=False),
    sa.Column('function_param_schema', sa.JSON(), nullable=False),
    sa.Column('function_source_code', sa.Text(), nullable=False),
    sa.Column('function_docstring', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['action_repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allowed_user_trigger',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.String(length=180), nullable=False),
    sa.Column('receiver', sa.String(length=30), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['llm_connection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_connection_ollama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['llm_connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiver', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['trigger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['trigger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_timer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['trigger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trigger_webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=70), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['trigger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('model_params', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['language_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allowed_chat_action',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE')
    )
    op.create_table('allowed_user_action',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    op.create_table('chat_exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('function_name', sa.String(length=80), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('function_name_semantically_valid', sa.Boolean(), nullable=False),
    sa.Column('params_semantically_valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allowed_agent_action',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE')
    )
    op.create_table('allowed_agent_trigger',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger.id'], ondelete='CASCADE')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('usermsg_exchange_id', sa.Integer(), nullable=True),
    sa.Column('reply_exchange_id', sa.Integer(), nullable=True),
    sa.Column('sending_agent_id', sa.Integer(), nullable=True),
    sa.Column('sending_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reply_exchange_id'], ['chat_exchange.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sending_agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['sending_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['usermsg_exchange_id'], ['chat_exchange.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usermsg_exchange_id')
    )
    op.create_table('event_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triggering_chat_exchange_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['triggering_chat_exchange_id'], ['chat_exchange.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monologue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('summary', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILURE', name='monologuestatus', native_enum=False), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message_markdown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['chat_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message_prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['chat_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thought',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('invocation_id', sa.Integer(), nullable=True),
    sa.Column('monologue_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invocation_id'], ['invocation.id'], ),
    sa.ForeignKeyConstraint(['monologue_id'], ['monologue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message_prompt_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message_prompt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message_prompt_option')
    op.drop_table('thought')
    op.drop_table('chat_message_prompt')
    op.drop_table('chat_message_markdown')
    op.drop_table('monologue')
    op.drop_table('event_chat')
    op.drop_table('chat_message')
    op.drop_table('allowed_agent_trigger')
    op.drop_table('allowed_agent_action')
    op.drop_table('invocation')
    op.drop_table('chat_exchange')
    op.drop_table('allowed_user_action')
    op.drop_table('allowed_chat_action')
    op.drop_table('agent')
    op.drop_table('trigger_webhook')
    op.drop_table('trigger_timer')
    op.drop_table('trigger_poll')
    op.drop_table('trigger_chat')
    op.drop_table('llm_connection_ollama')
    op.drop_table('language_model')
    op.drop_table('event')
    op.drop_table('chat')
    op.drop_table('allowed_user_trigger')
    op.drop_table('action')
    op.drop_table('user')
    op.drop_table('trigger')
    op.drop_table('llm_connection')
    op.drop_table('action_repository')
    # ### end Alembic commands ###
