"""add agent model params

Revision ID: 67fd1217f990
Revises: e2cfb759867d
Create Date: 2025-09-18 20:13:23.652987+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fd1217f990'
down_revision: Union[str, Sequence[str], None] = 'e2cfb759867d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('model_params', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'model_params')
    # ### end Alembic commands ###
