"""model id on delete set null

Revision ID: efcc72b4d99c
Revises: b0dc8bfb058d
Create Date: 2026-02-10 21:31:09.830383+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "efcc72b4d99c"
down_revision: Union[str, Sequence[str], None] = "b0dc8bfb058d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_agent_model_id_language_model"), "agent", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_agent_model_id_language_model"),
        "agent",
        "language_model",
        ["model_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_agent_model_id_language_model"), "agent", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_agent_model_id_language_model"),
        "agent",
        "language_model",
        ["model_id"],
        ["id"],
    )
    # ### end Alembic commands ###
